alias pjc="cd /home/urgen/Dropbox/for_dev/job4j/job4j_git/JavaCourse && min"
alias pjt="cd /home/urgen/Dropbox/for_dev/job4j/job4j_git/JavaCourse/chapter_002/target && min"
alias pja="cd ~/devexample/myproject && min"
alias pja1="cd /home/urgen/devexample/angular/spa && min"
alias pje="cd /home/urgen/devexample/java_example/ && min"
alias tree3="tree -L 3"
alias min="PROMPT_DIRTRIM=1"
alias p1="cd .."
alias p2="cd ../../"
alias p3="cd ../../../"
alias p4="cd ../../../../"
alias insrc="mkdir -p main/java/ru/job4j && mkdir -p test/java/ru/job4j"
alias la="ls -la"
alias form=":%!astyle"

